export const itemData = [
  {
    title: "Nano-assembly",
    slug: "nano-assembly",
    width: 800,
    height: 1200,
  },
  {
    title: "3D-Printing",
    slug: "3d-printing",
    width: 900,
    height: 600,
  },
  {
    title: "Falcon 9 & Heavy Nano-Assembly",
    slug: "falcon-9-and-heavy-nano-assembly",
    width: 800,
    height: 1000,
  },
  {
    title: "Starship Nano-assembly",
    slug: "starship-nano-assembly",
    width: 700,
    height: 900,
  },
  {
    title: "Starship Instant Reusability",
    slug: "starship-instant-reusability",
    width: 600,
    height: 800,
  },
  {
    title: "3D Printing Starships",
    slug: "3d-printing-starships",
    width: 1100,
    height: 600,
  },
  {
    title: "Nanoassembly-boosted SpaceX",
    slug: "nanoassembly-boosted-spacex",
    width: 800,
    height: 1100,
  },
  {
    title: "SpaceX automated with Optimi",
    slug: "spacex-automated-with-optimi",
    width: 750,
    height: 950,
  },
  {
    title: "Air Separation",
    slug: "air-separation",
    width: 950,
    height: 650,
  },
  {
    title: "Nano-Assembled Ground Works",
    slug: "nano-assembled-ground-works",
    width: 1200,
    height: 800,
  },
  {
    title: "Propellant Generation",
    slug: "propellant-generation",
    width: 800,
    height: 1200,
  },
  {
    title: "Terraforming Mars",
    slug: "terraforming-mars",
    width: 900,
    height: 600,
  },
  {
    title: "Compressing Mars Terraforming to 10 years",
    slug: "compressing-mars-terraforming-to-10-years",
    width: 800,
    height: 1000,
  },
  {
    title: "Solar System Habitation",
    slug: "solar-system-habitation",
    width: 700,
    height: 900,
  },
  {
    title: "Solar-powered Tesla",
    slug: "solar-powered-tesla",
    width: 600,
    height: 800,
  },
  {
    title: "Tesla automated with Optimi",
    slug: "tesla-automated-with-optimi",
    width: 1100,
    height: 600,
  },
  {
    title: "Direct Binary Code Generation",
    slug: "direct-binary-code-generation",
    width: 800,
    height: 1100,
  },
  {
    title: "Training AI models in minutes",
    slug: "training-ai-models-in-minutes",
    width: 750,
    height: 950,
  },
  {
    title: "xAI powered entirely with solar",
    slug: "xai-powered-entirely-with-solar",
    width: 950,
    height: 650,
  },
  {
    title: "xAIs 100M Rubin equivalent compute",
    slug: "xais-100m-rubin-equivalent-compute",
    width: 1200,
    height: 800,
  },
  {
    title: "Healing Autism",
    slug: "healing-autism",
    width: 800,
    height: 1200,
  },
  {
    title: "Overcoming serial attention limitation",
    slug: "overcoming-serial-attention-limitation",
    width: 900,
    height: 600,
  },
  {
    title: "Space-based Web Hosting",
    slug: "space-based-web-hosting",
    width: 920,
    height: 780,
  },
  {
    title: "Space-based Web Development Platform",
    slug: "space-based-web-development-platform",
    width: 1100,
    height: 650,
  },
  {
    title: "Space Launching Services",
    slug: "space-launching-services",
    width: 1100,
    height: 650,
  },
  {
    title: "Satellite Operation Services",
    slug: "satellite-operation-services",
    width: 650,
    height: 920,
  },
  {
    title: "Automation",
    slug: "automation",
    width: 850,
    height: 1150,
  },
];