export const itemData = [
  {
    title: "Nano-assembler",
    slug: "nano-assembler",
    width: 800,
    height: 1200,
  },
  {
    title: "Automated Design-Manufacturing Pipeline",
    slug: "automated-design-manufacturing-pipeline",
    width: 900,
    height: 600,
  },
  {
    title: "Nano-Assembled Starship",
    slug: "nano-assembled-starship",
    width: 800,
    height: 1000,
  },
  {
    title: "3D Printer for Starships",
    slug: "3d-printer-for-starships",
    width: 700,
    height: 900,
  },
  {
    title: "Fusion Starship",
    slug: "fusion-starship",
    width: 600,
    height: 800,
  },
  {
    title: "Instantly Reusable Launchpad",
    slug: "instantly-reusable-launchpad",
    width: 1100,
    height: 600,
  },
  {
    title: "Nano-Assembled Mechazilla",
    slug: "nano-assembled-mechazilla",
    width: 800,
    height: 1100,
  },
  {
    title: "Smart Starbase",
    slug: "smart-starbase",
    width: 750,
    height: 950,
  },
  {
    title: "Mass Driver",
    slug: "mass-driver",
    width: 950,
    height: 650,
  },
  {
    title: "Nano-Assembled Starlink",
    slug: "nano-assembled-starlink",
    width: 1200,
    height: 800,
  },
  {
    title: "Warp Drive",
    slug: "warp-drive",
    width: 800,
    height: 1200,
  },
  {
    title: "Nano-assembled Optimus",
    slug: "nano-assembled-optimus",
    width: 900,
    height: 600,
  },
  {
    title: "Nano-assembled Cybercab",
    slug: "nano-assembled-cybercab",
    width: 700,
    height: 900,
  },
  {
    title: "Nano-assembled Semi",
    slug: "nano-assembled-semi",
    width: 1100,
    height: 700,
  },
  {
    title: "Faster Factories",
    slug: "faster-factories",
    width: 800,
    height: 1000,
  },
  {
    title: "Alternative hardware for AI Training",
    slug: "alternative-hardware-for-ai-training",
    width: 950,
    height: 650,
  },
  {
    title: "Neuromorphic Computing",
    slug: "neuromorphic-computing",
    width: 1200,
    height: 800,
  },
  {
    title: "Photonic Computing",
    slug: "photonic-computing",
    width: 600,
    height: 900,
  },
  {
    title: "Engineering Simulation Tool",
    slug: "engineering-simulation-tool",
    width: 1200,
    height: 750,
  },
  {
    title: "Perspective Neuralink BCIs",
    slug: "perspective-neuralink-bcis",
    width: 900,
    height: 600,
  },
  {
    title: "Hardware",
    slug: "hardware",
    width: 800,
    height: 1100,
  },
  {
    title: "Regular & AI Data Centers in Space",
    slug: "regular-and-ai-data-centers-in-space",
    width: 1100,
    height: 650,
  },
  {
    title: "Quantum Data Centers in Space",
    slug: "quantum-data-centers-in-space",
    width: 1100,
    height: 650,
  },
];